#!/bin/bash -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PIDFILE=$DIR/foo.pid

source $DIR/utils.sh

case $1 in
  start)
    echo $$ > $PIDFILE
    while true; do sleep 10000; done
  ;;

  stop)
    kill_and_wait $PIDFILE 55
  ;;

  *)
    echo "Usage: foo {start|stop}"
  ;;
esac
