#!/bin/bash
service_instance=$1

guid=$(cf service ${service_instance} --guid)

if [[ -n "$service_instance" ]]; then
  bosh download manifest service-instance_${guid} /tmp/${guid}.yml
  bosh deployment /tmp/${guid}.yml
  # shift
  # $@
  bosh ssh
  rm /tmp/${guid}.yml
fi
